In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [3]:
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [4]:
np.full(10, 5.)

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [5]:
np.arange(10, 51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
np.random.randn(1)

array([ 1.12713093])

In [8]:
np.random.randn(25)

array([ -6.14255159e-01,   5.17696478e-01,   1.42257710e-01,
         5.22214933e-03,  -9.77154529e-01,   1.58033507e+00,
        -5.14962884e-01,  -8.24273831e-02,  -6.65276104e-01,
         2.56426293e-01,   5.14834820e-03,  -6.71729726e-04,
         4.38596511e-01,  -5.84145471e-01,  -4.55500545e-02,
         1.78433879e-01,  -3.68413473e-02,  -1.03640234e+00,
        -1.18530424e-01,  -2.20695847e-01,   4.16941342e-01,
        -1.14368111e+00,  -1.36306563e+00,   3.89370358e-01,
        -4.78555556e-01])

In [9]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [10]:
np.linspace(0, 1, 20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [11]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [13]:
mat[3, 4]

20

In [14]:
mat[:3, [1]]

array([[ 2],
       [ 7],
       [12]])

In [15]:
mat[4]

array([21, 22, 23, 24, 25])

In [16]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [17]:
np.sum(mat)

325

In [18]:
np.std(mat)

7.2111025509279782

In [19]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])